name: online_store
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  get: ^4.6.6
  dio: ^5.5.0+1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/placeholder.jpg
